import sys
import subprocess
from pathlib import Path
from playwright.sync_api import sync_playwright

def capture_m3u8_links(url: str) -> dict:
    m3u8_links = {}
    with sync_playwright() as p:
        print("Launching headless browser...")
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()

        def handle_request(request):
            if ".m3u8" in request.url:
                if "s0q1" in request.url and "s0q1" not in m3u8_links:
                    m3u8_links["s0q1"] = request.url
                elif "s1q1" in request.url and "s1q1" not in m3u8_links:
                    m3u8_links["s1q1"] = request.url
                elif "s2q1" in request.url and "s2q1" not in m3u8_links:
                    m3u8_links["s2q1"] = request.url

        page.on("request", handle_request)
        print(f"Navigating to: {url}")
        
        # Go to page and wait for it to fully load
        page.goto(url, wait_until="networkidle")
        
        # Look for the 'Play' button and click it to trigger the video streams
        try:
            print("Looking for a Play button...")
            play_btn = page.get_by_role("button", name="Play", exact=True)
            play_btn.wait_for(timeout=10000)
            play_btn.click()
            print("Clicked Play button, waiting for stream links...")
        except Exception as e:
            print("Could not find or click a specific Play button, trying a manual center click...")
            try:
                page.mouse.click(500, 500)
            except Exception:
                pass
        
        # Wait a few seconds to let the player requests go through
        page.wait_for_timeout(8000)
        
        # If we are missing some links, try interacting with the page more
        if len(m3u8_links) < 3:
            print("Did not find all links yet, interacting with the page to trigger stream load...")
            try:
                page.mouse.click(500, 500)
                page.wait_for_timeout(5000)
            except Exception:
                pass

        browser.close()
    return m3u8_links

def main():
    print("--- Echo360 Auto-Downloader ---")
    url = input("Enter Echo360 public link: ").strip()
    if not url:
        print("No URL provided.")
        sys.exit(1)

    links = capture_m3u8_links(url)
    
    if not links:
        print("Could not find any m3u8 links. The playback might require authentication or a manual click.")
        sys.exit(1)

    print(f"\nCaptured {len(links)} m3u8 stream links:")
    for k, v in links.items():
        print(f" - {k} URL captured")

    # Save to urls.txt so download_lecture.py can consume them
    script_dir = Path(__file__).resolve().parent
    urls_file = script_dir / "urls.txt"
    
    with urls_file.open("w", encoding="utf-8") as f:
        f.write("# Automatically generated by auto_download.py\n")
        f.write("# Source: " + url + "\n\n")
        for stream_url in links.values():
            f.write(stream_url + "\n")

    print("\nSaved URLs to urls.txt.")
    
    # Run the download script
    print("Executing download_lecture.py...")
    download_res = subprocess.run([sys.executable, "download_lecture.py"])
    
    if download_res.returncode != 0:
        print("\nDownload script encountered an error. Stopping.")
        sys.exit(download_res.returncode)
        
    # Run the merge script
    print("\nExecuting merge_voiceover.py...")
    merge_res = subprocess.run([sys.executable, "merge_voiceover.py"])
    
    if merge_res.returncode == 0:
        print("\n✅ All done! Your files are ready.")
    else:
        print("\nMerge script encountered an error.")
        sys.exit(merge_res.returncode)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(130)
