import sys
import subprocess
import re
from pathlib import Path
import concurrent.futures
from playwright.sync_api import sync_playwright

def capture_m3u8_links(url: str, safe_title: str) -> dict:
    m3u8_links = {}
    with sync_playwright() as p:
        print(f"[{safe_title}] Launching headless browser...")
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()

        def handle_request(request):
            if ".m3u8" in request.url:
                if "s0q1" in request.url and "s0q1" not in m3u8_links:
                    m3u8_links["s0q1"] = request.url
                elif "s1q1" in request.url and "s1q1" not in m3u8_links:
                    m3u8_links["s1q1"] = request.url
                elif "s2q1" in request.url and "s2q1" not in m3u8_links:
                    m3u8_links["s2q1"] = request.url

        page.on("request", handle_request)
        
        # Go to page and wait for it to fully load
        page.goto(url, wait_until="networkidle")
        
        # Look for the 'Play' button and click it to trigger the video streams
        try:
            play_btn = page.get_by_role("button", name="Play", exact=True)
            play_btn.wait_for(timeout=10000)
            play_btn.click()
        except Exception as e:
            try:
                page.mouse.click(500, 500)
            except Exception:
                pass
        
        # Wait a few seconds to let the player requests go through
        page.wait_for_timeout(8000)
        
        # If we are missing some links, try interacting with the page more
        if len(m3u8_links) < 3:
            try:
                page.mouse.click(500, 500)
                page.wait_for_timeout(5000)
            except Exception:
                pass

        browser.close()
    return m3u8_links

def process_item(title: str, url: str):
    # Create a safe folder name based on the title
    safe_title = re.sub(r'[\\/*?:"<>|]', "", title).strip()
    if not safe_title:
        safe_title = url.split("/")[-2] if "media/" in url else "Echo360_download"
    
    target_dir = Path.cwd() / safe_title
    target_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"\n[{safe_title}] Starting processing for URL: {url}")
    links = capture_m3u8_links(url, safe_title)
    
    if not links:
        print(f"[{safe_title}] Failed to find m3u8 links. The playback might require authentication or a manual click.")
        return False
        
    print(f"[{safe_title}] Captured {len(links)} m3u8 stream links.")
        
    urls_file = target_dir / "urls.txt"
    with urls_file.open("w", encoding="utf-8") as f:
        f.write("# Automatically generated by auto_download.py\n")
        f.write(f"# Source: {url}\n\n")
        for stream_url in links.values():
            f.write(stream_url + "\n")
            
    print(f"[{safe_title}] Downloading video chunks (Output redirected to download.log)...")
    download_script = Path.cwd() / "download_lecture.py"
    with open(target_dir / "download.log", "w") as log_f:
        dl_res = subprocess.run([sys.executable, str(download_script), str(target_dir)], stdout=log_f, stderr=subprocess.STDOUT)
        
    if dl_res.returncode != 0:
        print(f"[{safe_title}] Download script encountered an error. Check {target_dir / 'download.log'}")
        return False
        
    print(f"[{safe_title}] Merging video clips with audio...")
    merge_script = Path.cwd() / "merge_voiceover.py"
    with open(target_dir / "merge.log", "w") as log_f:
        merge_res = subprocess.run([sys.executable, str(merge_script), str(target_dir)], stdout=log_f, stderr=subprocess.STDOUT)
        
    if merge_res.returncode == 0:
        print(f"[{safe_title}] ✅ All done! Files are ready in the folder '{safe_title}'")
        return True
    else:
        print(f"[{safe_title}] Merge script encountered an error. Check {target_dir / 'merge.log'}")
        return False

def main():
    print("--- Echo360 Bulk Auto-Downloader ---")
    print("Paste your list containing names and links.")
    print("Example:\nLecture 19 Sequence Models and NLP: https://echo360.org/...\n")
    print("When you are done pasting, press Enter on an empty line TWICE to start.")
    
    lines = []
    empty_count = 0
    while True:
        try:
            line = input()
            if not line.strip():
                empty_count += 1
                if empty_count >= 2:
                    break
            else:
                empty_count = 0
                lines.append(line)
        except EOFError:
            break
            
    items_to_process = []
    for line in lines:
        # Extract http/https link
        match = re.search(r'(https?://[^\s]+)', line)
        if match:
            url = match.group(1)
            # Use anything leftover as the title, fallback to generic if empty
            title = line.replace(url, "").strip()
            # remove trailing colons or dashes from title
            title = re.sub(r'[:\-]+$', '', title).strip()
            items_to_process.append((title, url))
            
    if not items_to_process:
        print("No valid URLs found in the input. Stopping.")
        sys.exit(1)

    print(f"\nFound {len(items_to_process)} links. Starting parallel processing (max 4 concurrent downloads)...\n")
    
    # We use a ThreadPoolExecutor to run up to 4 processing tasks at the same time
    workers_count = min(len(items_to_process), 4)
    with concurrent.futures.ThreadPoolExecutor(max_workers=workers_count) as pool:
        # submit all tasks to the thread pool
        futures = [pool.submit(process_item, title, url) for title, url in items_to_process]
        
        # wait for everything to finish
        for future in concurrent.futures.as_completed(futures):
            future.result()

    print("\n🎉 Bulk download finished!")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(130)